name: workflow-ci-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy>=1.24.0
      - pandas>=2.0.0
      - scikit-learn>=1.3.0
      - mlflow>=2.10.0
      - joblib>=1.3.0
